Support --data-dir commandline argument
DominikDoom/a1111-sd-webui-tagcomplete pull request #142
Opened 2023-03-21 13:12 UTC by sumof2primes

- default ./

2023-03-22 09:52 UTC, DominikDoom requested changes
This does not work on Windows with just what you changed here, you need to make the main paths either all absolute or all relative. At least in the case of --data-dir being a relative path, which it is by default. Else path comparisons will fail.

It will also only work if your data dir is a subfolder of the webui itself, if it is outside of it or even on a different drive the script won't work at all in the first place since Gradio doesn't load the javascript for security reasons.

2023-03-22 09:52 UTC, DominikDoom commented on scripts/tag_autocomplete_helper.py
> +EXT_PATH = Path(data_path).joinpath('extensions')
```suggestion
EXT_PATH = Path(data_path).joinpath('extensions').absolute()
```

2023-03-22 09:52 UTC, DominikDoom commented on scripts/tag_autocomplete_helper.py
>  TAGS_PATH = Path(scripts.basedir()).joinpath('tags')
```suggestion
TAGS_PATH = Path(scripts.basedir()).joinpath('tags').absolute()
```

2023-03-26 04:21 UTC, sumof2primes commented
Ok. I understand --data-dir won't work expected for security reasons.
It's better to use below options separately for userdata.
--ckpt-dir
--vae-dir
--lora-dir
--embeddings-dir

2023-03-26 04:21 UTC, closed without merging